version: "3"

services:
  pubsub:
    image: ehacke/pubsub-emulator:latest
    environment:
      - PUBSUB_PROJECT_ID=project-test
      - PUBSUB_LISTEN_ADDRESS=0.0.0.0:8432
    ports:
      - "8432:8432"
