jobs:
  build:
    docker:
      - image: node:latest
      - image: ehacke/pubsub-emulator:latest
        name: firestore
        environment:
          - PUBSUB_PROJECT_ID=project-test
          - PUBSUB_LISTEN_ADDRESS=0.0.0.0:8432
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: testing
          command: npm run test
      - run:
          name: coverage
          command: npx codecov
workflows:
  version: 2
  test-and-build:
    jobs:
      - build
